/**
 * Fixtures.
 *
 * `state.egg.json` is a REAL payload generated by the engine (probe run,
 * egg-stage companion, empty bag/dex/catch_log, burn {}), with sprite paths
 * put through poketokenweb.api.public_state's rewrite, exactly as a browser
 * receives it.
 *
 * `state.mon.json` was produced by calling the engine's own
 * CompanionStore.payload()/shop_payload()/bag_payload()/dex_payload()/
 * catch_log_payload() and state.build() against a hand-seeded CompanionState —
 * so its field names are the engine's, not a guess. It carries a shiny
 * mid-line mon, a populated bag, a dex with is_raising entries, a catch_log
 * entry with caught_at: null, limits at 97%/82.5%, and a populated burn.
 */
import type { AppConfig, AppEvent, StatePayload } from '../types'
import egg from './state.egg.json'
import mon from './state.mon.json'

export const eggState = egg as unknown as StatePayload
export const monState = mon as unknown as StatePayload

export const defaultConfig: AppConfig = {
  refresh_interval: 120,
  warn_threshold: 80,
  crit_threshold: 95,
  limit_display_mode: 'both',
  language: 'en',
  growth_difficulty: 1,
  shop_difficulty: 1,
}

export const sampleEvents: AppEvent[] = [
  { kind: 'shiny', title: 'A shiny hatched!', detail: 'A shiny Pikachu — 1 in 512!', published_at: 1787196000 },
  { kind: 'graduated', title: 'Graduated!', detail: 'Venusaur joined your Pokedex.', published_at: 1787100000 },
  { kind: 'ditto', title: "Huh? It's Ditto!", detail: 'Your companion was a Ditto all along.', published_at: 1787000000 },
]

/** Deep copy so a test that mutates a fixture cannot leak into the next one. */
export function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T
}
